### PR TITLE
refs #000: add basic auth support

### PR DESCRIPTION
**Pull request by Monska85**

### CODE REVIEW

**Comment by paolomainardi** [comment]
This is great, thanks!

Can you please add the new variables to the README env variables section too? (not sure how much is updated, just focus on the new ones for now)

**Comment by Monska85** [comment]
> This is great, thanks!
> 
> Can you please add the new variables to the README env variables section too? (not sure how much is updated, just focus on the new ones for now)

I have updated the `README.md` with all the used variables. They are in the order that they appear in the code.

**Comment by paolomainardi** [comment]
LGTM

**Review by grota — APPROVED** [review]
as far as I can tell (which is not much :D ) it lgtm

**Comment by Bladedu** [comment]
LGTM

**Comment by paolomainardi** [comment]
Thanks 👍

**Pull request merged**
